import Header from "@/components/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import Provid from "@/ReduxSystem/Provider";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Goo-Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provid>
        <body className="bg-secondary-subtle">
          <Header />
          {children}
          <Footer />
        </body>
      </Provid>
    </html>
  );
}
